### ISSUE TITLE
panic on bolthold.Where("Something").In("something") (only with index)

### ISSUE THREAD

**Issue by HeavyHorst** [timshannon/bolthold#16]
```go
package main

import (
	"fmt"
	"log"

	"github.com/timshannon/bolthold"
)

type Person struct {
	Name     string
	Division string `boltholdIndex:"Division"`
}

var p1 = Person{"Hermann", "Division1"}

func main() {
	store, err := bolthold.Open("hold.db", 0666, nil)
	if err != nil {
		log.Fatalln(err)
	}

	store.Insert(p1.Name, p1)

	p1.Division = "test123"
	store.Update(p1.Name, p1)

	var result []Person
	err = store.Find(&result, bolthold.Where("Division").In("test123"))
	fmt.Println(result)
}
```

<details>
 <summary>panic</summary>

```shell
panic: reflect: New(nil)

goroutine 1 [running]:
reflect.New(0x0, 0x0, 0x1, 0x7f882f332000, 0x0)
	/usr/local/go/src/reflect/value.go:2130 +0x114
github.com/timshannon/bolthold.(*Criterion).test(0xc4200b25c0, 0x517400, 0xc4200b66c0, 0x40c701, 0x517400, 0xc4200b66c0, 0xc4200aba80)
	/home/rkaufmann/go/src/github.com/timshannon/bolthold/query.go:333 +0xce
github.com/timshannon/bolthold.matchesAllCriteria(0xc42000c4c8, 0x1, 0x1, 0x517400, 0xc4200b66c0, 0x1, 0xb, 0x7f882f2ce103, 0x27)
	/home/rkaufmann/go/src/github.com/timshannon/bolthold/query.go:397 +0x62
github.com/timshannon/bolthold.newIterator.func3(0xc4200aba00, 0xc4200b6680, 0x0, 0x0, 0x0, 0x506184, 0xc)
	/home/rkaufmann/go/src/github.com/timshannon/bolthold/index.go:250 +0x193
github.com/timshannon/bolthold.(*iterator).Next(0xc420012320, 0x0, 0x0, 0x606000, 0x0, 0x0, 0xc4200abc40)
	/home/rkaufmann/go/src/github.com/timshannon/bolthold/index.go:333 +0x188
github.com/timshannon/bolthold.runQuery(0xc420098380, 0x511220, 0xc4200b65e0, 0xc420018400, 0x0, 0x0, 0x0, 0x0, 0xc4200abd68, 0xc4200abd68, ...)
	/home/rkaufmann/go/src/github.com/timshannon/bolthold/query.go:497 +0x28b
github.com/timshannon/bolthold.findQuery(0xc420098380, 0x510160, 0xc4200b65c0, 0xc420018400, 0x1, 0xc420098380)
	/home/rkaufmann/go/src/github.com/timshannon/bolthold/query.go:602 +0x2f4
github.com/timshannon/bolthold.(*Store).TxFind(0xc42000c0d8, 0xc420098380, 0x510160, 0xc4200b65c0, 0xc420018400, 0xc4200abe20, 0xc420016180)
	/home/rkaufmann/go/src/github.com/timshannon/bolthold/get.go:58 +0x49
github.com/timshannon/bolthold.(*Store).Find.func1(0xc420098380, 0x553520, 0xc420098380)
	/home/rkaufmann/go/src/github.com/timshannon/bolthold/get.go:52 +0x4f
github.com/boltdb/bolt.(*DB).View(0xc42009e000, 0xc4200abe90, 0x0, 0x0)
	/home/rkaufmann/go/src/github.com/boltdb/bolt/db.go:629 +0x9f
github.com/timshannon/bolthold.(*Store).Find(0xc42000c0d8, 0x510160, 0xc4200b65c0, 0xc420018400, 0xc420018400, 0x0)
	/home/rkaufmann/go/src/github.com/timshannon/bolthold/get.go:53 +0x98
main.main()
	/home/rkaufmann/bolt.go:29 +0x309
exit status 2

```

</details>

**Comment by timshannon** [comment]
Thanks, I thought I specifically had a test case for this, but it must've been overlooked.

**Comment by timshannon** [comment]
Fixed in Master, thanks for the heads up.

**Comment by HeavyHorst** [comment]
Great, thanks for the quick fix !
