### ISSUE TITLE
Panic on ReIndex on empty/new store

### ISSUE THREAD

**Issue by ftKnox** [timshannon/bolthold#89]
I was looping over my databases running the ReIndex() on all of them. Any of the empty db's throw panics.

```go
2020/03/05 09:43:50 Opened database "users"
2020/03/05 09:43:50 Panic found, shutting down [runtime error: invalid memory address or nil pointer dereference]
2020/03/05 09:43:50 goroutine 1 [running]:
main.main.func1()
        /Users/user/code/app/app.go:42 +0xdb
panic(0x1525560, 0x1b112e0)
        /opt/local/lib/go/src/runtime/panic.go:679 +0x1b2
go.etcd.io/bbolt.(*Bucket).Cursor(...)
        /opt/local/src/go.etcd.io/bbolt/bucket.go:84
github.com/timshannon/bolthold.(*Store).ReIndex.func1(0xc000146000, 0xc000144001, 0xc000146000)
        /opt/local/src/github.com/timshannon/bolthold/store.go:99 +0x2d0
go.etcd.io/bbolt.(*DB).Update(0xc00012e200, 0xc0000f9c68, 0x0, 0x0)
        /opt/local/src/go.etcd.io/bbolt/db.go:694 +0xa8
github.com/timshannon/bolthold.(*Store).ReIndex(0xc00013e000, 0x15a8240, 0xc000144000, 0xc000136088, 0x4, 0x8, 0x0, 0x0)
        /opt/local/src/github.com/timshannon/bolthold/store.go:79 +0xc5```

**Comment by ftKnox** [comment]
awesome! confirmed working, thanks Tim!
