### ISSUE TITLE
Crashes when getting an object of a type not previously registered.

### ISSUE THREAD

**Issue by calmh** [timshannon/bolthold#9]
That is,

```
type Foo ...

var result Foo
db.Get("someKey", &result)
```

results in

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x141679d]

goroutine 23 [running]:
testing.tRunner.func1(0xc420122340)
	/usr/local/go/src/testing/testing.go:621 +0x554
panic(0x1557dc0, 0x184c690)
	/usr/local/go/src/runtime/panic.go:489 +0x2ee
github.com/boltdb/bolt.(*Bucket).Get(0x0, 0xc4200d4b10, 0x11, 0x40, 0x0, 0x20, 0x0)
	/Users/jb/src/github.com/boltdb/bolt/bucket.go:257 +0x5d
github.com/timshannon/bolthold.(*Store).TxGet(0xc42008a188, 0xc420123450, 0x1538de0, 0xc4201541a0, 0x151b680, 0xc420121ee0, 0x1420bee, 0xc4200e3c70)
	/Users/jb/src/github.com/timshannon/bolthold/get.go:33 +0x18b
github.com/timshannon/bolthold.(*Store).Get.func1(0xc420123450, 0x15e4268, 0xc420123450)
	/Users/jb/src/github.com/timshannon/bolthold/get.go:19 +0x74
github.com/boltdb/bolt.(*DB).View(0xc4200776c0, 0xc4200e3cf0, 0x0, 0x0)
	/Users/jb/src/github.com/boltdb/bolt/db.go:578 +0xc7
github.com/timshannon/bolthold.(*Store).Get(0xc42008a188, 0x1538de0, 0xc4201541a0, 0x151b680, 0xc420121ee0, 0x0, 0xc4200e3d90)
	/Users/jb/src/github.com/timshannon/bolthold/get.go:20 +0x106
...
```

apparently because the bucket doesn't exist when the get happens. (I'll try to fix this.)

**Comment by timshannon** [comment]
Yeah I thought I handled that, but looking at the code I'm only handling it on Write operations.

Thanks for the report, I'll get it fixed and write up a test case for it.

**Comment by timshannon** [comment]
Looks like I handled this in Find, but not get.

Thanks for the PR.
