### ISSUE TITLE
Panic when embedded struct is nil

### ISSUE THREAD

**Issue by ftKnox** [timshannon/bolthold#94]
Looks like there is a reflection issue when the embedded struct is a nil pointer. I tried to figure this one out, but it's beyond me.

```go
ERROR: reflect: indirection through nil pointer to embedded struct
STACK:
goroutine 23 [running]:

        /opt/local/lib/go/src/runtime/panic.go:679 +0x1b2
reflect.Value.FieldByIndex(0x15c13e0, 0xc0002ce7e0, 0x199, 0xc0003b6be0, 0x2, 0x2, 0x0, 0x1692f60, 0x1502120)
        /opt/local/lib/go/src/reflect/value.go:876 +0x39c
reflect.Value.FieldByName(0x15c13e0, 0xc0002ce7e0, 0x199, 0x14df6db, 0x5, 0x199, 0xc00039b058, 0xc0003b2180)
        /opt/local/lib/go/src/reflect/value.go:892 +0x104
_/Users/user/code/app/lib/bolthold.(*Store).newStorer.func1.1(0x14df6db, 0x5, 0x14e2b40, 0xc0002ca470, 0x4, 0xc0003b6b70, 0x9, 0x10, 0x16833c0)
        /Users/user/code/app/lib/bolthold/store.go:225 +0xfa
_/Users/user/code/app/lib/bolthold.(*Store).updateIndexes(0xc0003055a0, 0x1687180, 0xc000305e80, 0x16833c0, 0xc00030e460, 0xc0002b50b0, 0x26, 0x30, 0x14e2b40, 0xc0002ca470, ...)
        /Users/user/code/app/lib/bolthold/index.go:47 +0x103
_/Users/user/code/app/lib/bolthold.(*Store).addIndexes(...)
        /Users/user/code/app/lib/bolthold/index.go:35
_/Users/user/code/app/lib/bolthold.(*Store).upsert(0xc0003055a0, 0x16833c0, 0xc00030e460, 0x1502120, 0xc0003b02f0, 0x14e2b40, 0xc0002ca470, 0x0, 0x0)
        /Users/user/code/app/lib/bolthold/put.go:273 +0x460
```

**Comment by ftKnox** [comment]
So I looked at this again and this patch fixes the panic. I am not sure what, if any, repercussions this has for indexing

```diff

diff --git a/store.go b/store.go
index ad74409..970a2db 100644
--- a/store.go
+++ b/store.go
@@ -258,15 +258,20 @@ func (s *Store) newStorer(dataType interface{}) Storer {
                }
        }
 
+       value := reflect.ValueOf(dataType).Elem()
        for i := 0; i < storer.rType.NumField(); i++ {
                field := storer.rType.Field(i)
                if field.Anonymous {
-                       anonType := field.Type
-                       if anonType.Kind() == reflect.Ptr {
-                               anonType = anonType.Elem()
-                       }
-                       for j := 0; j < anonType.NumField(); j++ {
-                               addIndex(anonType.Field(j))
+                       //check if the field value is nil
+                       if !value.FieldByName(field.Name).IsNil() {
+                               anonType := field.Type
+                               if anonType.Kind() == reflect.Ptr {
+                                       anonType = anonType.Elem()
+                               }
+
+                               for j := 0; j < anonType.NumField(); j++ {
+                                       addIndex(anonType.Field(j))
+                               }
                        }
                } else {
                        addIndex(field)
```

**Comment by ftKnox** [comment]
looks good so far
